cart/urls.py
from django.urls import path
from .views import add_to_cart, view_cart, remove_from_cart, update_quantity

app_name = 'cart'

urlpatterns = [
    path('add/<int:item_id>/', add_to_cart, name='add_to_cart'),
    path('view/', view_cart, name='view_cart'),
    path('remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update/<int:item_id>/', update_quantity, name='update_quantity'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Core features
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),

    # Auth routes
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # App-specific routes
    path('menu/', include('menu.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('qr/', include('qrcodes.urls')),
    path('users/', include('users.urls')), 
    path('accounts/login/', auth_views.LoginView.as_view()),
     path('login/', auth_views.LoginView.as_view(template_name='your_app/custom_login.html'), name='login'),

]

users/urls.py
from django.urls import path
from .views import ProfileView, UserRegistrationView
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Password change
    path('password/change/', auth_views.PasswordChangeView.as_view(template_name='app/changepassword.html', form_class=MyPasswordChangeForm, success_url='/users/password/change/done/'), name='changepassword'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='app/passwordchangedone.html'), name='passwordchangedone'),

    # Password reset
    path('password/reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html', form_class=MyPasswordResetForm), name='password_reset'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_resized import ResizedImageField
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse_lazy

class User(AbstractUser):
    name = models.CharField(max_length=200)
    email = models.EmailField(unique=True, max_length=200)
    profile_image = ResizedImageField(
        upload_to='users/images/profiles/', null=True, blank=True, size=[250, 250], quality=75, force_format='PNG',
        help_text='size of logo must be 250*250 and format must be png image file', crop=['middle', 'center']
    )
    phone_number = PhoneNumberField(null=True, blank=True)

    REQUIRED_FIELDS = ["username"]
    USERNAME_FIELD = "email"

    class Meta:
        ordering = ['-id']
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

    def delete(self, *args, **kwargs):
        self.profile_image.delete(save=True)
        super(User, self).delete(*args, **kwargs)


@receiver(post_save, sender=settings.AUTH_USER_MODEL, dispatch_uid="user_registered")
def on_user_registration(sender, instance, created, **kwargs):
    """
    :TOPIC if user creates at any point the statistics model will be initialized
    :param sender:
    :param instance:
    :param created:
    :param kwargs:
    :return:
    """
    pass

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import password_validation
from django.utils.translation import gettext as _
from .models import User

class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password (again)', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        labels = {'email': 'Email'}
        widgets = {'username': forms.TextInput(attrs={'class': 'form-control'})}

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control'}))

class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Old Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control', 'autofocus': True}))
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}))

class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label=_("Email"), max_length=254, widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class': 'form-control'})) 

class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("Confirm New Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control'}),
    )

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'phone_number', 'profile_image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_image': forms.FileInput(attrs={'class': 'form-control'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', widget=forms.TextInput(attrs={'class': 'form-control'}))

users/views.py
from django.urls import reverse_lazy
from django.shortcuts import  render
from django.views import View
from .models import User
from .forms import UserRegistrationForm, UserProfileForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views.generic import CreateView

class UserRegistrationView(CreateView):
    form_class = UserRegistrationForm
    template_name = 'app/customerregistration.html'
    object_context_name = 'form'
    success_url = reverse_lazy('website:home')
    success_message = 'Registration successful!'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(UserRegistrationView, self).form_valid(form)

@method_decorator(login_required, name='dispatch')
class ProfileView(View):
    def get(self, request):
        form = UserProfileForm(instance=request.user)
        return render(request, 'app/profile.html', {'form': form, 'active': 'btn-primary'})
      
    def post(self, request):
        form = UserProfileForm(request.POST, instance=request.user)  
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Profile has been updated!')
        return render(request, 'app/profile.html', {'form': form, 'active': 'btn-primary'})


def login(request):
    return render(request, 'app/login.html')

users/templates/app/changepassword.html
{% extends "base.html" %}
{% load static %}
{% block title %}Change Passowrd{% endblock title %}
{% block content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome <span class="text-capitalize">{{request.user}}</span></h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    <li class="d-grid"><a href="{% url 'users:profile' %}" class="btn btn-primary">Change Password</a></li>
    
  </ul>
  </div>
  <div class="col-sm-9 offset-sm-1">
    <hr>
    <form action="" method="post" novalidate class="shadow p-5">
         {% csrf_token %}
         {% for fm in form %}
         <div class="form-group"> {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br> </div>
         {% endfor %}
         <input type="submit" class = "btn btn-primary mt-4" value = "Submit">
         <br>
         
         {% if form.non_field_errors %}
             {% for error in form.non_field_errors  %}
             <p class="alert alert-danger my-3">{{error}}</p>
             {% endfor %}
         {% endif %}
             
    </form>
  </div>
 </div>
</div>
{% endblock content %}

users/templates/app/customerregistration.html
{% extends "base.html" %}
{% load static %}
{% block title %}Sign Up{% endblock title %}

{% block content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Dont have an account? Sign Up Here!</h3>
   <hr>
   <form action="" method="post" novalidate class="shadow p-5">
      
      {% if messages %}
         {% for message in messages %}

         <p {% if message.tags %} class = "alert alert-{{message.tags}} mb-5" {% endif %} > {{message}} </p>
         
         {% endfor %}         
      {% endif %}
         
      {% csrf_token %}
      {% for fm in form %}
      <div classs = "form-group mb-3"> {{ fm.label_tag }} {{fm}} <small class = "text-danger" >{{fm.errors|striptags}}</small></div>
      {% endfor %}
      <div class="text-center mb-3">
        <button type="submit" class="btn btn-primary px-5">Submit</button>
      </div>
      <div class="text-center text-primary fw-bold">
        <small>Existing User? <a href="{% url 'users:login' %}" class="text-danger">Login Now</a></small>
      </div>
      {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
      <p class="alert alert-danger my-3">{{ error }}</p>
      {% endfor %}
      {% endif %}
  </form>
  
  </div>
 </div>
</div>
{% endblock content %}

users/templates/app/login.html
{% extends "base.html" %}
{% load socialaccount %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Login</h3>
   <hr>
   <form action="" method="post" novalidate class="shadow p-5">
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group"> {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br> </div>
        {% endfor %}
        <small> <a href=" {% url 'users:password_reset' %} "> Forgot Password ?</a> </small> <br>
        <input type="submit" class = "btn btn-primary mt-4" value = "Login">
        <br>
        
        <h3>Or login with</h3>
<a href="{% provider_login_url 'google' %}">Google</a><br>
        <div class="text-center text-primary fw-bold"> <small> <a href=" {% url 'users:register' %} ">New To website ?</a> </small></div>
        
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors  %}
            <p class="alert alert-danger my-3">{{error}}</p>
            {% endfor %}
        {% endif %}
            
   </form>
  </div>
 </div>
</div>
{% endblock content %}

users/templates/app/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password Reset{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Reset Password</h3>
            <hr>
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group"> {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br> </div>
                {% endfor %}
                <input type="submit" class = "btn btn-primary mt-4" value = "Submit">
                <br>
         
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors  %}
                <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
                {% endif %}
             
            </form>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/app/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password Reset Complete{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h4 >Password Reset Completed !</h4>
            <div><iframe src="https://giphy.com/embed/ibolLe3mOqHE3PQTtk" width="200" height="200"  class="giphy-embed"  frameborder="0" allowFullScreen ></iframe></div>
        </div>    
    </div>
</div>
{% endblock content %}

users/templates/app/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password Reset Confirm{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Reset Password Confirm</h3>
            <hr>
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group"> {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br> </div>
                {% endfor %}
                <input type="submit" class = "btn btn-primary mt-4" value = "Submit">
                <br>
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors  %}
                <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
                {% endif %}
             
            </form>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/app/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password Reset Done{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h4 class="alert-heading">Well done!</h4>
            <p>An Email has been sent with instructions to reset your password. <b>Check Your Email!</b> </p>
        </div>    
    </div>
</div>

{% endblock content %}

users/templates/app/passwordchangedone.html
{% extends "base.html" %}
{% load static %}
{% block title %}Change Password Done{% endblock title %}
{% block content %}


<div class="container my-5 ">

    <div class="row">
        <h3>Welcome <span class="text-capitalize">{{request.user}}</span></h3>
        <div class="col-sm-2 border-end ">
            <ul class="list-unstyled">
                <li class="d-grid">
                    <a href="{% url 'users:profile' %}" class="btn btn-primary">Change Password Done</a>
                </li>
            </ul>
        </div>
        <div class="col-sm-9 offset-sm-1 text-center"> <h3> Password Changed Successfully!!</h3>
        <div><iframe src="https://giphy.com/embed/ibolLe3mOqHE3PQTtk" width="200" height="200"  class="giphy-embed"  frameborder="0" allowFullScreen ></iframe></div>
        
        </div>
    </div>
</div>


{% endblock content %}

users/templates/app/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile{% endblock title %}
{% block content %}
<div class="container my-5">
 <div class="row">
  <h3>Welcome <span class="text-capitalize">{{request.user}}</span></h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    <li class="d-grid"><a href="{% url 'users:profile'  %}" class="btn {{active}}">Profile</a></li>
   </ul>
  </div>
  <div class="col-sm-8 offset-sm-1">
   <form action="" method="post" novalidate>
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group"> {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br> </div>
                {% endfor %}
                <input type="submit" class = "btn btn-primary mt-4" value = "Submit">
                <br>
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors  %}
                <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
                {% endif %}
   </form>
   
   {% if messages %}
         {% for message in messages %}

         <p {% if message.tags %} class = "alert alert-{{message.tags}} mb-5" {% endif %} > {{message}} </p>
         
         {% endfor %}         
      {% endif %}
    
  </div>
 </div>
</div>
{% endblock content %}